# Generated by Django 4.2.29 on 2026-03-14 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_contact_id_alter_experience_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
