# Generated by Django 4.2.29 on 2026-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_experience_order_alter_project_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('Tools', 'Tools'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
